### ISSUE TITLE
Add global and local configuration enable/disable the opentelemetry

### ISSUE THREAD

**Issue by v1v** [cyrille-leclerc/opentelemetry-plugin#9]
### What

I'd like to discuss the below features:

* To disable/enable open tracing globally.
* To implicitly enable opentelemetry for all the pipelines.
* To disable/enable open tracing per pipeline.

#### With `JCasC:

Being able to configure the plugin globally and implicitly o explicitly for all the pipelines.

```yaml
  openTelemetry:
    endpoint: "otel-collector-contrib:4317"
    useTls: false
    implicit: false // whether to be implicitly loaded for all the pipelines
    enabled: true  // whether to disable/enable the integration globally, let's say if some performance issue or connectivity issues could affect the jenkins instance
```

#### With pipeline

```groovy
pipeline {
  agent any
  options {
    openTelemetry true
  }
  stages {
    stage('foo') {
      steps {
        sh(label: 'foo', script: "echo bar")
      }
    }
  }
}
```
